server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: <some uri for the repo with stored configuration, will be specified later>
          default-label: main
          clone-on-start: true
          timeout: 5
          force-pull: true